"use client";
import { createClient, type User } from "@supabase/supabase-js";
import { FormEvent, useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import styles from "./page.module.css";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const auth=url&&key?createClient(url,key):null;
type Mode="login"|"signup"|"reset"|"update";
export default function AccountPage(){
 const [mode,setMode]=useState<Mode>("login");const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(Boolean(auth));const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{if(!auth)return;let active=true;auth.auth.getUser().then(({data})=>{if(active){setUser(data.user);setLoading(false);}}).catch(()=>{if(active){setLoading(false);setMessage("Unable to load your account. Please try again.");}});const {data:{subscription}}=auth.auth.onAuthStateChange((event,session)=>{setUser(session?.user??null);if(event==="PASSWORD_RECOVERY")setMode("update");});return()=>{active=false;subscription.unsubscribe();};},[]);
 function switchMode(next:Mode){setMode(next);setMessage("");}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!auth){setMessage("Customer accounts are currently unavailable. Please try again later.");return;}const form=e.currentTarget;const data=new FormData(form);const email=String(data.get("email")??"").trim();const password=String(data.get("password")??"");setBusy(true);setMessage("");try{if(mode==="login"){const {error}=await auth.auth.signInWithPassword({email,password});if(error)throw error;}else if(mode==="signup"){const {data:result,error}=await auth.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/account`}});if(error)throw error;setMessage(result.session?"Your account is ready.":"Check your email for a confirmation link, then return to sign in.");}else if(mode==="reset"){const {error}=await auth.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/account`});if(error)throw error;setMessage("If an account exists for this email, you’ll receive a password reset link.");}else{const {error}=await auth.auth.updateUser({password});if(error)throw error;setMode("login");setMessage("Your password has been updated.");}form.reset();}catch(error){setMessage(error instanceof Error?error.message:"Something went wrong. Please try again.");}finally{setBusy(false);}}
 async function logout(){if(!auth)return;setBusy(true);const {error}=await auth.auth.signOut();setBusy(false);if(error)setMessage("Unable to sign out. Please try again.");else{setUser(null);setMode("login");setMessage("");}}
 const signedIn=user&&mode!=="update";
 return <main className={styles.page}><div className={styles.visual}><Image src="/images/s1.jpeg" alt="Refined everyday essentials in navy" fill loading="eager" sizes="(max-width: 700px) 100vw, 50vw"/><div><p className="eyebrow">Your world, considered.</p><h2>Make yourself<br /><em>at home.</em></h2></div></div><section className={styles.panel}><p className="eyebrow">HKFitness / My account</p><h1>{signedIn?"Welcome back.":mode==="signup"?"Join our world.":mode==="reset"?"A fresh start.":mode==="update"?"A new password.":"Welcome back."}</h1>{loading?<p role="status">Loading your account…</p>:signedIn?<><p>You’re signed in as <strong>{user.email}</strong>.</p><div className={styles.accountLinks}><Link href="/apparel">Explore the collection ↗</Link><Link href="/cart">View your shopping bag ↗</Link><Link href="/contact">Contact customer care ↗</Link></div><button className="text-link" disabled={busy} onClick={logout}>Sign out</button></>:<><p>{mode==="signup"?"Create your customer account.":mode==="reset"?"Enter your email and we’ll send a reset link.":mode==="update"?"Choose a new password for your account.":"Sign in to your personal corner of HKFitness."}</p>{!auth&&<p className="form-status">Customer accounts are currently unavailable. Please check back soon.</p>}<form onSubmit={submit} key={mode}>{mode!=="update"&&<div className="form-field"><label htmlFor="account-email">Email address</label><input id="account-email" name="email" type="email" autoComplete="email" required maxLength={254}/></div>}{mode!=="reset"&&<div className="form-field"><label htmlFor="account-password">{mode==="update"?"New password":"Password"}</label><input id="account-password" name="password" type="password" autoComplete={mode==="login"?"current-password":"new-password"} minLength={mode==="login"?1:8} maxLength={128} required/>{mode!=="login"&&<small>At least 8 characters.</small>}</div>}{mode==="login"&&<button className={styles.forgot} type="button" onClick={()=>switchMode("reset")}>Forgot password?</button>}<button className="button" disabled={busy||!auth} type="submit">{busy?"Please wait…":mode==="signup"?"Create account":mode==="reset"?"Send reset link":mode==="update"?"Update password":"Sign in"}<span>→</span></button></form><div className={styles.switch}>{mode==="login"?<>New to HKFitness? <button onClick={()=>switchMode("signup")}>Create an account</button></>:<button onClick={()=>switchMode("login")}>Back to sign in</button>}</div></>}<p className="form-status" role="status">{message}</p></section></main>;
}


